spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/