server:
  port: 8082

mybatis:
#  type-aliases-package: com.yz.crm.service.bean
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql
spring:
  datasource:
    url: jdbc:mysql://195144146.tpddns.cn:3306/yzdatabase?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 1
    min-idle: 1
    max-active: 20

eureka:
#  instance:
#    non-secure-port: ${service.port:8082}
  client:
    service-url:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
pagehelper:
  helper-dialect: mysql #PageHelper默认会检测当前数据库的url，自动选择相应的数据库方言。您可以配置helperDialect属性来指定方言。
                        #您可以使用下面的缩写：
                        #oracle，mysql，mariadb，sqlite，hsqldb，postgresql， db2，sqlserver
                        #informix，h2，sqlserver2012，derby。
  row-bounds-with-count: true #rowBoundsWithCount：默认值为false，当此参数设置true为时，PageHelper将执行计数查询
  page-size-zero: true #pageSizeZero：默认值为false，当此参数设置为时true，如果pageSize=0或RowBounds.Limit = 0将查询所有结果（相当于未执行分页查询，但结果的返回类型仍为Page）。
